### ISSUE TITLE
Python3.3 compatibility

### ISSUE THREAD

**Issue by LordK1** [anishmenon/django-realtime#8]
hi brow , im workin on Python3 an find when using this package  import simplejson as json raised thi error from django.utils import simplejson as json
ImportError: cannot import name 'simplejson' and then update from this repository but still there is error on this line , after i search about it, i find python3.3 has "json" package instead of "simplejson" and when   import simplejson as json changed into import json it works as well as ...
thanks and goodluck .

**Comment by anishmenon** [comment]
Fixed :

https://github.com/anishmenon/django-realtime/commit/1efeb5e0859fe51d62086d1a1c42585db63b83ea

**Comment by jassi5887** [comment]
Hi Anish,

For me this is still not fixed. I used your git repo to install on my dev environment and that was ok but when I try to install on heroku using "pip install django-realtime" I still get this simplejson issue.
